dist: trusty
sudo: required
language: generic
matrix:
  include:
    - os: linux
      env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
      addons:
        apt:
          packages:
            - g++-5
          sources: &sources
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
script:
- wget https://curl.haxx.se/download/curl-7.54.0.tar.gz
- tar xvzf curl-7.54.0.tar.gz
- rm curl-7.54.0.tar.gz
- ls
- cd curl-7.54.0
- ./configure
- make
- sudo make install
- ls
- cd
- ls
- cd
- ls

- find -name libcurl.a
- find -name *.a
- find -name *.lib

- cd build/akosoj/TechProject
- mkdir build
- cd build
- cmake .. && make
